### ISSUE TITLE
component.mjs 里面的moonbit.memory是啥？

### ISSUE THREAD

**Issue by kimi996z** [peter-jerry-ye/canvas#1]
原版不可运行，改为
memory = new WebAssembly.Memory({ initial: 10, maximum: 1000 })
后可以运行。

**Comment by peter-jerry-ye** [comment]
已修复。

memory是WebAssembly的线性内存，用于高效传递字符串和数组等JS数据。本周构建系统修改了导出内存的行为，改为默认不导出，因此不可运行。

**Comment by kimi996z** [comment]
谢谢
