### ISSUE TITLE
例子无法运行起来， memory包中有好几个编译错误

### ISSUE THREAD

**Issue by jimwei** [peter-jerry-ye/canvas#4]
例子无法运行起来， memory包中有好几个编译错误

**Comment by peter-jerry-ye** [comment]
等到 https://issues.chromium.org/issues/380911432 修复之后再修，不然同样也跑不起来

**Comment by jimwei** [comment]
[like]  WeiYaPeng(Jim) reacted to your message:
________________________________

**Comment by peter-jerry-ye** [comment]
Issue fixed.

**Comment by jimwei** [comment]
[heart]         WeiYaPeng(Jim) reacted to your message:
________________________________
